{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Gestión de errores\n",
    "\n",
    "-----------------------"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Un regalo de jubilación inolvidable\n",
    "\n",
    "\n",
    "![](https://www.infodefensa.com/images/showid2/5006020?w=900&mh=700)\n",
    "\n",
    "¿Hace un paseo de Rafale, *monsieur*?\n",
    "\n",
    "En 2020 un empleado de Dassault recibió un regalo de jubilación muy especial: un paseo en un Rafale, el caza estrella de la empresa aeronaútica. \n",
    "\n",
    "El empleado de 64 años, no deseaba de ninguna manera hacer eso y estaba francamente nervioso, pero sus a sus compañeros les hacía tanta ilusión que decidió aceptar.\n",
    "\n",
    "Nada más subirse, su corazón ya estaba a 140 latidos por segundo, razón más que suficiente para cancelar el *paseo* en alguien de su edad. Le santaron en el asiento de atrás, y a nadie se le ocurrió comprobar que su traje anti-g estaba mal puesto, el cinturón mal abrochado, la máscara de oxígeno suelta y el casco también.\n",
    "\n",
    "En vez de un despegue suave, a 10º de ascenso, el piloto decidió darle el despegue estandar de un caza a 47º, sometiendo al jubilado a una aceleración de 4G, lo cual hizo que su cuerpo pesase más de 300 Kg.\n",
    "\n",
    "Nuestro heroe, que no tenía oxígeno y estaba mal fijado al asiento, al verse sacudido de un lado para otro y aplastado contra el asiento,se agarró a lo que pudo.\n",
    "\n",
    "Por suerte, logró encontrar una barra metálica en la parte superior del asiento:la palanca de eyección.\n",
    "\n",
    "Después una explosión y la descompresión de la cabina, *monsieur le jubilé* fué lanzado al aire con un cohete debajo de su asiento. La fuerza fue tal que su casco y mascarilla de oxígeno mal colocados salieron volando.\n",
    "\n",
    "Por suerte, nuestro heroe (que ahora debe de tener pánico a volar) aterrizó sano y salvo. El piloto, que por un error de software no fue eyectado también logró mal que bien, aterrizar su *descapotable*.\n",
    "\n",
    "[Podeis ver el informe completo que es una verdadera maravilla de la literatura cómica](https://www.aerotime.aero/articles/24788-fighter-jet-crash-averted-by-defect-in-civil-ejection-incident)\n",
    "\n",
    "> Moraleja: las cagadas pasan y hay que estar preparado"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Los errores en software\n",
    "\n",
    "Los errores son una parte inevitable de cualquier sistema complejo, y el software no es una excepción. Para poder gestionarlos, lo primero es enteder qué tipos de error pueden ocurrir:\n",
    "\n",
    "* errores del dominio\n",
    "* pánicos\n",
    "* errores externos\n",
    "\n",
    "#### Errores del Dominio\n",
    "\n",
    "> Todo software simula algo del mundo real: un sistema de facturación de una empresa, el mercado de valores, una batalla contrra zombies, etc. A eso que se simula, se le llama el **Dominio** del software.\n",
    "\n",
    "Los errores de dominio son normales y esperados como parte del proceso y tienen que ser incluídos dentro del diseño del software.\n",
    "\n",
    "Por ejemplo, una factura puede ser rechazada por el departamento de pagos por tener un código incorrecto.\n",
    "\n",
    "La empresa seguramente ya tiene un proceso para gestionar esto y debe de verse reflejado en el software.\n",
    "\n",
    "#### Pánicos\n",
    "\n",
    "Son errores inesperados que dejan el sistema en un estado desconocido. Pueden venir de fuera de tu software (el ordenador se queda sin memoria) o ser causados por un descuido del programador (dividir por cero).\n",
    "\n",
    "El software no puede recuperarse de un *pánico*.\n",
    "\n",
    "\n",
    "#### Errores Externos\n",
    "\n",
    "Son errores que se tienen que esperar como parte de la arquitectura o despliegue del software, pero que no son parte del domini del software. \n",
    "\n",
    "Vienen de fuera.\n",
    "\n",
    "Por ejemplo, una conexión a una API falla, un servidor de autenticación está caído o una llamada de red produce un *timeout*.\n",
    "\n",
    "El software debe de recuperarse de este tipo de errores y posiblemente volver a intentar la operación pasado un rato.\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestión de errores en Python\n",
    "\n",
    "En Python, los errores se gestionan mediante el uso de excepciones. Una excepción es un evento que ocurre durante la ejecución de un programa que interrumpe el flujo normal del programa. Cuando ocurre una excepción, Python detiene la ejecución del programa actual y pasa el control a un bloque de código designado para manejar excepciones, si existe alguno.\n",
    "\n",
    "\n",
    "**Lanzamiento de excepciones**\n",
    "\n",
    "Puedes lanzar una excepción en Python utilizando la palabra clave `raise`. Por ejemplo:\n",
    "\n",
    "```python\n",
    "raise ValueError(\"This is a custom error message\")\n",
    "```\n",
    "\n",
    "En este caso, se lanza una excepción `ValueError` con un mensaje personalizado.\n",
    "\n",
    "**Captura de excepciones**\n",
    "\n",
    "\n",
    "![](https://files.realpython.com/media/try_except.c94eabed2c59.png)\n",
    "\n",
    "Para capturar una excepción y manejarla, puedes usar los bloques de código `try` y `except`. Por ejemplo:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # Código que puede lanzar una excepción\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    # Código que se ejecuta cuando se lanza la excepción\n",
    "    print(\"You can't divide by zero!\")\n",
    "```\n",
    "\n",
    "Aquí, si el código dentro del bloque `try` lanza una excepción `ZeroDivisionError`, el código dentro del bloque `except` se ejecutará.\n",
    "\n",
    "**Si necesitas acceso a la excepción en sí**\n",
    "\n",
    "A veces no basta con saber que se ha lanzado un excepción, necesito acceso a la excepción en sí porque contiene algo de información extra. Esto se hace de la siguiente manera:\n",
    "\n",
    "```Python\n",
    "try:\n",
    "    main()\n",
    "except FileNotFoundError as file_error:\n",
    "    print(file_error)\n",
    "except AssertionError as assert_error:\n",
    "    print(assert_error)\n",
    "```\n",
    "\n",
    "\n",
    "**Tipos de excepciones**\n",
    "\n",
    "Hay muchas excepciones integradas en Python que puedes utilizar para manejar diferentes tipos de errores:\n",
    "\n",
    "* `ValueError`: El valor es incorrecto. Por ejemplo, me esperaba un `int` positivo, y me has dado un `int`, pero negativo.\n",
    "*  `TypeError`: El tipo es incorrecto. Por ejemplo, me esperaba un `float` y me has pasado un `str`. \n",
    "*  `IndexError`: Indice de una secuencia incorrecto\n",
    "*  `AssertionError`: Un `assert` ha dado `False`.\n",
    "*  y muchas más.\n",
    "\n",
    "**Mejores prácticas**\n",
    "\n",
    "- Usa excepciones para manejar errores, no para controlar el flujo normal del programa.\n",
    "- Cuando captures excepciones, intenta ser lo más específico posible (es decir, captura `ValueError`, no solo `Exception`) para evitar ocultar otros errores.\n",
    "- Considera usar la declaración `finally` para especificar las acciones de limpieza que deben ser ejecutadas independientemente de si se produce una excepción en el bloque `try`.\n",
    "- Asegúrate de que los mensajes de error son claros y útiles, para que puedas entender qué causó el error cuando lo veas.\n",
    "- No captures una excepción a menos que puedas hacer algo al respecto (por ejemplo, corrigiendo el problema, proporcionando un valor por defecto, etc.). De lo contrario, deja que la excepción se propague hacia arriba.\n",
    "- Avanzado (más adelante): Puedes definir tus propias excepciones personalizadas creando una nueva clase que herede de la clase base `Exception`. Esto puede ser útil si necesitas manejar tipos de errores específicos de tu aplicación."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestión de errores en otros lenguajes\n",
    "\n",
    "Las excepciones existen en prácticamente todos los lenguajes de programación y puedes usarlas sin miedo.\n",
    "\n",
    "Sin embargo, en algunos lenguajes éstas quedan reservadas para errores más graves o inesperados (pánicos y errores externos). Para los errores menos graves (los del dominio) se devuelve un tipo especial llamado `Result` que no existe en Python.\n",
    "\n",
    "Un buen ejemplo de esto son [Swift](https://developer.apple.com/documentation/swift/result) o [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) (en desarrolo móvil).\n",
    "\n",
    "Javascript funciona de manera similar a Python en este caso.\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Mejores Prácticas\n",
    "\n",
    "Software profesional debe de:\n",
    "\n",
    "* tener todas las funciones que puedan lanzar excepciones dentro de un bloque `try/except`\n",
    "* registrar todos los errores que ocurren\n",
    "* sobrevivir a los errores de dominio y errores externos\n",
    "\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Registro de errores\n",
    "\n",
    "Hay muchas herramientas para esto, algunas especializadas para aplicaciones móviles y otras para aplicaciones web.\n",
    "\n",
    "Para **aplicaciones móviles**, algunas de las más habituales son:\n",
    "\n",
    "* [Crashlytics](https://firebase.google.com/products/crashlytics/)\n",
    "* [Bugsnag](https://www.bugsnag.com/)\n",
    "  \n",
    "\n",
    "  Para **aplicaciones web**, las más comunes son:\n",
    "\n",
    "  * [Sentry](https://sentry.io/welcome/)\n",
    "  * [Logstash](https://www.elastic.co/es/logstash/)\n",
    "\n",
    "\n",
    "La información recopilada por estos sistemas es **vital para descubrir bugs o ataques** a un software que está en producción.\n",
    "\n",
    "> Nunca, jamás de los jamases saques software a producción sin tener esto implementado."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestión de errores de dominio\n",
    "\n",
    "Si es posible gestionar el error dentro de la propia función donde se produce, sin tener que lanzar excepciones, hazlo.\n",
    "\n",
    "Las excepciones *contaminan* el código y reducen su legibilidad. Usalas sólo cuando haga falta.\n",
    "\n",
    "1. Lanza una excepción personalizada en el foco del error\n",
    "2. Captúrala lo más cerca del error posible, regístrala, gestiona y subsana el fallo.\n",
    "3. El software no puede caerse por esto.\n",
    "4. Avisa al usuario si es necesaria su intervención."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestión de pánicos\n",
    "\n",
    "La función inicial que arranca el software debe de estar dentro de un bloque `try/except` que captura todas las excepciones, las registra y deja que el software se caiga.\n",
    "\n",
    "```Python\n",
    "\n",
    "# ejemplo\n",
    "try:\n",
    "    \n",
    "    game_loop()\n",
    "\n",
    "except Exception as error: # captura cualquier cosa\n",
    "    log_error(error)       # lo mandamos a sentry o lo que sea\n",
    "    print(¡Se jodió la vaina, maifrén!) # Avisamos al usuario \n",
    "                                        # que se acabó y dejamos que se caiga "
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestion de errores externos\n",
    "\n",
    "Debes de avisar al usuario y hacer lo posible para subsanarlo. A veces es simplemente volver a intentar más tarde.\n",
    "\n",
    "1. Lanza una excepción personalizada en el foco del error\n",
    "2. Captúrala lo más cerca del error posible, regístrala, gestiona y subsana el fallo.\n",
    "3. El software no puede caerse por esto.\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Vamos a aplicar todo esto en nuestra función `read_user_choice`"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
